#!/bin/sh
# A Simple shortcut to run a program dependant on the
# Avcom API's. For this script, the shared library path
# is in the same directory as the application, and not
# in a standard library path.
#
# Script below will run application "debugger":
#   $ ./run debugger
#
LD_LIBRARY_PATH="." ./$@
